apiVersion: v2
appVersion: 1.5.3
description: OctoPrint is the snappy web interface for your 3D printer
name: octoprint
version: 1.5.3
kubeVersion: ">=1.16.0-0"
keywords:
- octoprint
- 3d
- printer
home: https://github.com/k8s-at-home/charts/tree/master/charts/octoprint
icon: https://avatars3.githubusercontent.com/u/5982294?s=400&v=4
sources:
- https://github.com/OctoPrint/OctoPrint
- https://hub.docker.com/r/octoprint/octoprint
maintainers:
- name: TrueCharts
  email: info@truecharts.org
  url: truecharts.org
- name: fherbert
  email: francois@herbert.org.nz
dependencies:
- name: common
  repository: https://truecharts.org/
  version: 3.5.2
