apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: bitwarden
version: 1.2.5
upstream_version: 2.1.5
appVersion: "auto"
description: Unofficial Bitwarden compatible server written in Rust
type: application
deprecated: false
home: https://github.com/truecharts/apps/tree/master/incubator/bitwarden
icon: https://raw.githubusercontent.com/bitwarden/brand/master/icons/256x256.png
keywords:
  - bitwarden
  - bitwardenrs
  - bitwarden_rs
  - password
  - rust
sources:
  - https://github.com/truecharts/apps/tree/master/incubator/bitwarden
  - https://github.com/k8s-at-home/charts/tree/master/charts/stable/bitwardenrs
  - https://github.com/dani-garcia/bitwarden_rs
dependencies:
  - name: common
    repository: https://truecharts.org/
    version: 3.5.5
    # condition:
  - name: postgresql
    version: 10.4.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: truecharts.org
  - name: Ornias1993
    email: kjeld@schouten-lebbing.nl
    url: truecharts.org
# annotations:
