# Default values for Tautulli.

image:
  repository: ghcr.io/truecharts/tautulli
  pullPolicy: IfNotPresent
  tag: v2.7.2

strategy:
  type: Recreate

services:
  main:
    port:
      port: 8181

env: {}
  # TZ: UTC
  # PUID: 1001
  # PGID: 1001

persistence:
  config:
    enabled: true
    mountPath: "/config"
    emptyDir: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: ""
