# Default values for Home Assistant

image:
  repository: homeassistant/home-assistant
  pullPolicy: IfNotPresent
  tag: 2021.5.0

strategy:
  type: Recreate

# Configure the Security Context for the Pod
podSecurityContext:
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0
  supplementalGroups: [5, 20, 24]

env: {}
    # TZ:

services:
  main:
    port:
      port: 8123
    nodePort: 30023

# # Enable devices to be discoverable
# hostNetwork: true

# # When hostNetwork is true set dnsPolicy to ClusterFirstWithHostNet
# dnsPolicy: ClusterFirstWithHostNet

# # Enable passing thru a USB device to Home Assistant
# securityContext:
#   privileged: true

# Allow access a Git repository by passing in a private SSH key
git:
  # Raw SSH private key
  deployKey: ""
  # Base64-encoded SSH private key. When both variables are set, the raw SSH key takes precedence.
  deployKeyBase64: ""

# Enable a prometheus-operator servicemonitor
prometheus:
  serviceMonitor:
    enabled: false
    # interval: 1m
    # additionalLabels: {}

persistence:
  config:
    enabled: true
    mountPath: "/config"
    emptyDir: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: ""

# # Path to your Z-Wave / Zigbee device in the container
# additionalVolumeMounts:
#   - name: zwave-usb
#     mountPath: /dev/serial/by-id/usb-0658_0200-if00

# # Path to your Z-Wave / Zigbee device on the host
# additionalVolumes:
#   - name: zwave-usb
#     hostPath:
#       path: /dev/serial/by-id/usb-0658_0200-if00

# Enabled mariadb
# ... for more options see https://github.com/bitnami/charts/tree/master/bitnami/mariadb
mariadb:
  enabled: false
  architecture: standalone
  auth:
    database: home-assistant
    username: home-assistant
    password: home-assistant-pass
    rootPassword: home-assistantrootpass
  primary:
    persistence:
      enabled: false
      # storageClass: ""

# Enabled postgres
# ... for more options see https://github.com/bitnami/charts/tree/master/bitnami/postgresql
postgresql:
  enabled: false
  postgresqlUsername: home-assistant
  postgresqlPassword: home-assistant-pass
  postgresqlDatabase: home-assistant
  persistence:
    enabled: false
    # storageClass: ""

# Enable influxdb
# ... for more options see https://github.com/bitnami/charts/tree/master/bitnami/influxdb
influxdb:
  enabled: false
  architecture: standalone
  database: home_assistant
  authEnabled: false
  persistence:
    enabled: false
    # storageClass: ""
    # size: 8Gi
