# Default values for emby.

image:
  repository: ghcr.io/truecharts/emby
  pullPolicy: IfNotPresent
  tag: v4.5.4.0

strategy:
  type: Recreate

# 44=video 107=render
# Configure the Security Context for the Pod
podSecurityContext:
  supplementalGroups: [44, 107]

services:
  main:
    port:
      port: 8096

persistence:
  config:
    enabled: true
    mountPath: "/config"
    emptyDir: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: ""
