image:
  repository: collabora/code
  tag: 6.4.8.4
  pullPolicy: IfNotPresent

strategy:
  type: Recreate

# Configure the Security Context for the Pod
podSecurityContext:
  runAsNonRoot: false
  runAsUser: null
  runAsGroup: null
  fsGroup: null

services:
  main:
    type: NodePort
    port:
      port: 9980
      nodePort: 30980

env:
  domain: nextcloud\.domain\.tld
  dictionaries: de_DE en_GB en_US es_ES fr_FR it nl pt_BR pt_PT ru
  username: admin
  password: changeme
  extra_params:
  server_name: collabora\.domain\.tld
