# Default values for KMS.

image:
  repository: pykmsorg/py-kms
  pullPolicy: IfNotPresent
  tag: minimal

strategy:
  type: Recreate

# Configure the Security Context for the Pod
podSecurityContext:
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0

services:
  main:
    port:
      port: 1688
