image:
  repository: jlesage/handbrake
  tag: v1.23.2
  pullPolicy: IfNotPresent

strategy:
  type: Recreate

startAsRoot: true

# Configure the Security Context for the Pod
podSecurityContext:
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0
  supplementalGroups: [24, 44, 107]

services:
  main:
    port:
      port: 5800
  vnc:
    enabled: true
    type: ClusterIP
    port:
      port: 5900
      protocol: "TCP"
      targetPort: 5900

# All values here are set as the docker defaults.
envTpl:
# Permissions Settings
  USER_ID: "{{ .Values.PUID }}"
  GROUP_ID: "{{ .Values.PGID }}"

env:
# General Settings
  KEEP_APP_RUNNING: "0"
  CLEAN_TMP_DIR: "1"
# GUI Settings
  DISPLAY_WIDTH: "1280"
  DISPLAY_HEIGHT: "768"
  SECURE_CONNECTION: "0"
  VNC_PASSWORD:
# Automated Conversion Preset
  AUTOMATED_CONVERSION_PRESET: "General/Very Fast 1080p30"
  AUTOMATED_CONVERSION_FORMAT: "mp4"
  AUTOMATED_CONVERSION_KEEP_SOURCE: "1"
  AUTOMATED_CONVERSION_NON_VIDEO_FILE_ACTION: "ignore"

persistence:
  config:
    enabled: true
    mountPath: "/config"
    emptyDir: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: ""
