# Default values for Plex.

image:
  repository: ghcr.io/truecharts/plex
  pullPolicy: IfNotPresent
  tag: v1.22.0.4163-d8c4875dd

strategy:
  type: Recreate

# 44=video 107=render
podSecurityContext:
  supplementalGroups: [44, 107]

services:
  main:
    port:
      port: 32400

persistence:
  config:
    enabled: true
    mountPath: "/config"
    emptyDir: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: ""
