# Default values for esphome.

image:
  repository: esphome/esphome
  pullPolicy: IfNotPresent
  tag: 1.17.1

strategy:
  type: Recreate

services:
  main:
    port:
      port: 6052

env: {}
  # ESPHOME_DASHBOARD_USE_PING: true
  # ESPHOME_DASHBOARD_RELATIVE_URL: "/"
  # ESPHOME_QUICKWIZARD:
  # ESPHOME_IS_HASSIO:
  # DISABLE_HA_AUTHENTICATION:
  # USERNAME:
  # PASSWORD:

persistence:
  config:
    enabled: true
    mountPath: "/config"
    emptyDir: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: ""
