# Default values for Transmission.

image:
  repository: ghcr.io/truecharts/transmission
  pullPolicy: IfNotPresent
  tag: v3.00

strategy:
  type: Recreate

services:
  main:
    port:
      port: 9091
  tcp:
    enabled: true
    type: ClusterIP
    port:
      port: 51413
      protocol: TCP
      targetPort: 51413
  udp:
    enabled: true
    type: ClusterIP
    port:
      port: 51413
      protocol: UDP
      targetPort: 51413


env: {}
  # TZ: UTC
  # PUID: 1001
  # PGID: 1001

persistence:
  config:
    enabled: true
    mountPath: "/config"
    emptyDir: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: ""


## TrueCharts Values

transmissionConfig:
  bind-address-ipv4: "0.0.0.0"
  bind-address-ipv6: ::"
  cache-size-mb: 4
  lpd-enabled: false
  dht-enabled: true
  peer-congestion-algorithm: ""
  message-level: 2
  peer-id-ttl-hours: 4
  peer-port: 51413
  peer-port-random-high: 65535
  peer-port-random-low: 49152
  peer-port-random-on-start: false

transmissionFixedConfig:
  peer-socket-tos: "default"
  pex-enabled: true
  port-forwarding-enabled: false
  preallocation: 0
  prefetch-enabled: true
  rename-partial-files: true
  rpc-authentication-required: false
  rpc-bind-address: "0.0.0.0"
  rpc-enabled: true
  rpc-host-whitelist: ""
  rpc-host-whitelist-enabled: false
  rpc-password: "CHANGEME"
  rpc-port: 9091
  rpc-url: "/transmission/"
  rpc-username: ""
  rpc-whitelist: ""
  rpc-whitelist-enabled: false
  umask: 2
  utp-enabled: true
  watch-dir: "/watch"
  watch-dir-enabled: true
