apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: jellyfin
version: 3.1.5
upstream_version: 4.2.1
appVersion: "auto"
description: Jellyfin is a Free Software Media System
type: application
deprecated: false
home: https://github.com/truecharts/apps/tree/master/stable/jellyfin
icon: https://truecharts.org/_static/img/jellyfin-icon.png
keywords:
  - jellyfin
  - plex
  - emby
sources:
  - https://github.com/truecharts/apps/tree/master/stable/jellyfin
  - https://github.com/k8s-at-home/charts/tree/master/charts/jellyfin
  - https://hub.docker.com/r/linuxserver/Jellyfin/
  - https://github.com/jellyfin/jellyfin
dependencies:
  - name: common
    repository: https://truecharts.org/
    version: 3.5.5
    # condition:
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: truecharts.org
  - name: Ornias1993
    email: kjeld@schouten-lebbing.nl
    url: truecharts.org
# annotations:
