# Default values for jellyfin.

image:
  repository: jellyfin/jellyfin
  pullPolicy: IfNotPresent
  tag: 10.7.5

strategy:
  type: Recreate

# 44=video 107=render
podSecurityContext:
  supplementalGroups: [44, 107]

services:
  main:
    port:
      port: 8096

persistence:
  config:
    enabled: true
    mountPath: "/config"
    emptyDir: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: ""
